### ISSUE TITLE
12/07 할일 리스트

### ISSUE THREAD

**Issue by YoonJieut** [KDT-IaaS-Class-One-Group/introduceTeam#28]
### 12/07 할일 리스트업

- [x] 코드리뷰 : 각자 진행 후, 리펙토링 진행 여부 논의
- [x] 전환로직 : 다른 클릭했을 때, 바로 뜨는 것 
- [x] 스타일링 : 소개 내부 스타일링

**Comment by hmoongi94** [comment]
(따봉)
