### ISSUE TITLE
docs : teamMembers내에 info 내용 정하기

### ISSUE THREAD

**Issue by forhn37** [KDT-IaaS-Class-One-Group/introduceTeam#31]
**1. info내에 언제쯤 내용 넣을지의 시점**
오늘 내용 작성 or 내일 오전
2. **info 내용 정하기**
2-1. 기존에 작성했던 내용을 info에 innerhtml형태로 넣을지 (``빽틱사용)
2-2. 새로운 내용을 info에 텍스트 형식으로 넣을지

위의 선택사항에 대해 논의

**Comment by forhn37** [comment]
info내용 innerhtml로 작성하기로 결정
@YoonJieut 
담당자 결정

**Comment by hmoongi94** [comment]
info란 css 작성 -> 여기 이슈에서 하겠습니다.
@hmoongi94 
담당자
