### ISSUE TITLE
feat: memberDiv 클릭 시 갱신 문제

### ISSUE THREAD

**Issue by personarpgg** [KDT-IaaS-Class-One-Group/introduceTeam#48]
클릭 후 팀원 정보가 갱신 된 후 애니메이션이 출력되는 문제가 있습니다

문제점)
클릭 -> 정보갱신 -> 애니메이션 작동(-100%) -> 니메이션 작동(0%) 

해결점)
클릭 -> 애니메이션 작동(-100%) -> 정보 갱신 -> 애니메이션 작동(0%)

**Comment by hmoongi94** [comment]
해결완료 pull/request 했습니다.
